#!/usr/bin/env bash
# install-hermes.sh — activates hermes-agent wrapper
# Generated by home-manager; edits will be overwritten.
set -e

HERMES_ROOT="$HOME/.local/hermes-agent"
HERMES_VENV="$HERMES_ROOT/.venv"
HERMES_BIN="$HERMES_VENV/bin"
HERMES_CONFIG_DIR="${HERMES_CONFIG_DIR:-$HOME/.hermes}"
UV_CACHE_DIR="$HOME/.cache/uv"

mkdir -p "$HOME/.local/bin"

cat > "$HOME/.local/bin/hermes" << 'WRAPPER'
#!/usr/bin/env bash
set -e
export HERMES_CONFIG_DIR="${HERMES_CONFIG_DIR}"
export UV_CACHE_DIR="${UV_CACHE_DIR}"
export PATH="${HERMES_BIN}:$PATH"
exec "${HERMES_BIN}/hermes" "$@"
WRAPPER

chmod +x "$HOME/.local/bin/hermes"
